
set_property MARK_DEBUG true [get_nets {counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {counter_reg[4]}]
set_property MARK_DEBUG true [get_nets {counter_reg[7]}]
set_property MARK_DEBUG true [get_nets {counter_reg[15]}]
set_property MARK_DEBUG true [get_nets {counter_reg[16]}]
set_property MARK_DEBUG true [get_nets {counter_reg[18]}]
set_property MARK_DEBUG true [get_nets {counter_reg[19]}]
set_property MARK_DEBUG true [get_nets {counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {counter_reg[12]}]
set_property MARK_DEBUG true [get_nets {counter_reg[17]}]
set_property MARK_DEBUG true [get_nets {counter_reg[10]}]
set_property MARK_DEBUG true [get_nets {counter_reg[6]}]
set_property MARK_DEBUG true [get_nets {counter_reg[23]}]
set_property MARK_DEBUG true [get_nets {counter_reg[21]}]
set_property MARK_DEBUG true [get_nets {counter_reg[5]}]
set_property MARK_DEBUG true [get_nets {counter_reg[8]}]
set_property MARK_DEBUG true [get_nets {counter_reg[9]}]
set_property MARK_DEBUG true [get_nets {counter_reg[20]}]
set_property MARK_DEBUG true [get_nets {counter_reg[22]}]
set_property MARK_DEBUG true [get_nets {counter_reg[11]}]
set_property MARK_DEBUG true [get_nets {counter_reg[13]}]
set_property MARK_DEBUG true [get_nets {counter_reg[14]}]
set_property MARK_DEBUG true [get_nets led_0_OBUF]
set_property C_CLK_INPUT_FREQ_HZ 12000000 [get_debug_cores dbg_hub]



